pipeline {
    agent any
	stages {
	    stage('Checkout code') {
			steps {
				checkout scm
			}
        }
        stage('Build') {
	        tools {
                jdk "Java 17"
                maven "LOCALMAVEN"
            }
            steps {
                sh 'mvn clean deploy -DskipTests=true'
            }
        }        
    }
    post {
        always {
            cleanWs()
        }
    }
}
